### ISSUE TITLE
Issue with 5780 year

### ISSUE THREAD

**Issue by amaneshi** [kfirba/Hebdate#1]
If someone interested in solving this bug in file Kfirba\Support\HebrewNumerology add to const numerology[] first item ["" => 0] or ["-" => 0] (native speakers knows better). The lib is awesome, and if author will fix this will be even better.

**Comment by kfirba** [comment]
Hey @amaneshi,

Thanks for reporting!

Can you please elaborate more about the issue? A reproduction with current behavior and expected behavior would be awesome.

**Comment by amaneshi** [comment]
I tried to use 
`GregorianDate::toJewish('11/10/2019')->format(Format::HEBREW_FULL)->convert()`
and got error:

> "message": "Undefined offset: 0",
    "exception": "ErrorException",
    "file": "C:\\OneDrive\\Projects\\WWW\\mahsevon-back\\vendor\\kfirba\\hebdate\\src\\Support\\HebrewNumerology.php",
    "line": 180,

As jewish year end with "0" (current 5780) which not exist in numerology array.

**Comment by kfirba** [comment]
I see. I’ll take a look at it next week.

Thanks!

**Comment by kfirba** [comment]
@amaneshi Along with other fixes, this issue should be resolved now.

Thanks for reporting!
